import img from '../../../assets/advix_photo.png'
import background from '../../../assets/background_advix.png'
export const data = [
	{
		id: 19,
		User_id: 3445465,
		Category: 'SMM и маркетинг',
		language: 'русский',
		id_telegram: -45456567,
		desc_channel: 'Отличный канал! Условия в ЛС!',
		link_Cannel: 'https://t.me/gdf5455gh',
		link_Type_Boolean: true,
		name_channel: 'Advix: новости',
		url_Image_Channel: img,
		url_background_channel: background,
		public_type: true,
		count_subscribers: 54574,
		count_views: 445026,
		ERR: 20,
		position: 2,
		default_price: 70000,
		CPM: 500,
		default_time_day: [24, 48, 0],
		hot_price: 0,
		hot_state: false,
		hot_date: new Date('2024-04-25'),
		currently_date: new Date(),
	},
	{
		id: 20,
		User_id: 3445465,
		Category: 'SMM и маркетинг',
		language: 'русский',
		id_telegram: -45456567,
		desc_channel: 'Отличный канал! Условия в ЛС!',
		link_Cannel: 'https://t.me/gdf5455gh',
		link_Type_Boolean: true,
		name_channel: 'Test: новости',
		url_Image_Channel: img,
		url_background_channel: background,
		public_type: true,
		count_subscribers: 5257,
		count_views: 99912,
		ERR: 25,
		position: 2,
		default_price: 90000,
		CPM: 100,
		default_time_day: [24, 72, 2],
		hot_price: 0,
		hot_state: false,
		hot_date: new Date('2024-04-25'),
		currently_date: new Date(),
	},
	{
		id: 20,
		User_id: 3445465,
		Category: 'SMM и маркетинг',
		language: 'русский',
		id_telegram: -45456567,
		desc_channel: 'Отличный канал! Условия в ЛС!',
		link_Cannel: 'https://t.me/gdf5455gh',
		link_Type_Boolean: true,
		name_channel: 'Test: новости',
		url_Image_Channel: img,
		url_background_channel: background,
		public_type: true,
		count_subscribers: 5257,
		count_views: 99912,
		ERR: 25,
		position: 2,
		default_price: 90000,
		CPM: 100,
		default_time_day: [24, 72, 2],
		hot_price: 0,
		hot_state: false,
		hot_date: new Date('2024-04-25'),
		currently_date: new Date(),
	},

	{
		id: 20,
		User_id: 3445465,
		Category: 'SMM и маркетинг1',
		language: 'русский',
		id_telegram: -45456567,
		desc_channel: 'Отличный канал! Условия в ЛС!',
		link_Cannel: 'https://t.me/gdf5455gh',
		link_Type_Boolean: true,
		name_channel: 'Test: новости',
		url_Image_Channel: img,
		url_background_channel: background,
		public_type: true,
		count_subscribers: 5257,
		count_views: 99912,
		ERR: 25,
		position: 2,
		default_price: 80000,
		CPM: 100,
		default_time_day: [24, 72, 2],
		hot_price: 19990,
		hot_state: true,
		hot_date: new Date('2024-04-25'),
		currently_date: new Date(),
	},
]
